### ISSUE TITLE
Время, проведенное в игре, не суммируется с предыдущим.

### ISSUE THREAD

**Issue by KhalilovaIrina** [Logerr23/javaqa-team-diplom#1]
# Описание
При вызове метода *play* внутри метода *sumGenre*, возвращается изначальное значение времени, заданное при установке игры - 0.

# Локализация дефекта
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/Player.java#L35
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/Player.java#L36

# Шаги воспроизведения:
1. Открыть код программы https://github.com/Logerr23/javaqa-team-diplom.git в IDE, ветка *player*.
2. Запустить тест *shouldSumGenreIfOneGame()*.

*Ожидаемый результат* : Тест пройден
*Фактический результат* : Тест провален. Фактический результат 0.

# Скриншот
![Баг1](https://user-images.githubusercontent.com/117723193/215349461-99dcc9ca-f4aa-4159-bec0-6ddcb4bdc63d.png)

# Окружение
* **Операционная система: Windows 10 Pro**
* **IDEA: IntelliJ IDEA 2022.3 (Community Edition**
* **Java: OpenJDK11**

**Comment by Logerr23** [comment]
<img width="1029" alt="Снимок экрана 2023-01-31 в 14 13 59" src="https://user-images.githubusercontent.com/112762989/215745222-57d2f103-be0a-4982-a35a-aad4b262b630.png">

**Comment by Logerr23** [comment]
<img width="1029" alt="Снимок экрана 2023-01-31 в 14 13 59" src="https://user-images.githubusercontent.com/112762989/215745736-900d0219-8fa7-4fe6-8ae5-1b0497b57a97.png">
