### ISSUE TITLE
Возвращается NULL вместо игры, в которую из указанного жанра, было сыграно больше всего

### ISSUE THREAD

**Issue by KhalilovaIrina** [Logerr23/javaqa-team-diplom#2]
# Описание
При вызове метода *mostPlayerByGenre* при наличии игры и времени игры в нее больше 0, возвращается NULL

# Локализация дефекта
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения:
1. Открыть код программы https://github.com/Logerr23/javaqa-team-diplom.git в IDE, ветка player.
2. Запустить тест *mostPlayerByGenre()*.

*Ожидаемый результат* : Тест пройден
*Фактический результат* : Тест провален. Фактический результат NULL.

# Скриншот
![Баг2](https://user-images.githubusercontent.com/117723193/215349442-6d086d3f-b328-4de0-8fb7-80cb91681877.png)

# Окружение
* **Операционная система: Windows 10 Pro**
* **IDEA: IntelliJ IDEA 2022.3 (Community Edition**
* **Java: OpenJDK11**

**Comment by Logerr23** [comment]
<img width="1189" alt="Снимок экрана 2023-01-31 в 14 18 11" src="https://user-images.githubusercontent.com/112762989/215746095-47941c4d-349e-4c46-a115-eb4b021894e8.png">
