### ISSUE TITLE
Отсутствует сообщение класса RuntimeExeption Игрок может играть неустановленную игру

### ISSUE THREAD

**Issue by KhalilovaIrina** [Logerr23/javaqa-team-diplom#3]
# Описание
Игрок может играть в игру, которая не установлена. 

# Локализация дефекта
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/Player.java#L35
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/Player.java#L36
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/Player.java#L37
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/Player.java#L38

# Шаги воспроизведения:
1. Открыть код программы https://github.com/Logerr23/javaqa-team-diplom.git в IDE, ветка player.
2. Запустить тест *shouldThrowIfNoInstallWhenPlay()*.

*Ожидаемый результат* : Тест пройден.
*Фактический результат* : Тест провален. Отсутствует сообщение RuntimeExeption.

# Скриншот
![Баг3](https://user-images.githubusercontent.com/117723193/215433373-eab1c1fb-0f9f-40b5-82a9-194d65d71afb.png)

# Окружение
* **Операционная система: Windows 10 Pro**
* **IDEA: IntelliJ IDEA 2022.3 (Community Edition**
* **Java: OpenJDK11**

**Comment by Logerr23** [comment]
<img width="1287" alt="Снимок экрана 2023-01-31 в 14 19 54" src="https://user-images.githubusercontent.com/112762989/215746450-7eb9750c-0f7d-4c07-b4f7-81baf6e88ab0.png">
