### ISSUE TITLE
Метод containsGame не находит последнюю добавленную игру в каталог

### ISSUE THREAD

**Issue by Logerr23** [Logerr23/javaqa-team-diplom#4]
# Описание
Если, методом containsGame, проверять наличие последней добавленной игры в каталог, метод будет возвращать false.

# Локация дефекта
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/GameStore.java#L32

# Шаги Воспроизведения

1. Открыть [код программы](https://github.com/Logerr23/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
1. Воспроизвести тест shouldAddGames
1. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест проходит
*Фактический результат:* Тест не проходит

# Скриншот
<img width="1184" alt="Снимок экрана 2023-01-30 в 12 54 29" src="https://user-images.githubusercontent.com/112762989/215445102-c8829a31-f5ad-4e87-bc10-27e09a3dea41.png">

#Окружение
* **Операционная система:** macOS Monterey 12.6
* **IDE:** intelliJ IDEA 2022.2.4 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by KhalilovaIrina** [comment]
![4](https://user-images.githubusercontent.com/117723193/215748404-b947d7bb-5a2c-4279-89e5-f9e681ccb854.png)
