### ISSUE TITLE
В каталог можно добавлять одинаковые игры

### ISSUE THREAD

**Issue by Logerr23** [Logerr23/javaqa-team-diplom#5]
# Описание
Метод publishGame, перед добавлением новых игр, не проверяет каталог на наличие игр с идентичными названиями и жанром.
В каталог добавляются игры с одинаковыми названиями и жанром.

# Локация дефекта
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/GameStore.java#L22

# Шаги Воспроизведения

1. Открыть [код программы](https://github.com/Logerr23/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
1. Воспроизвести тест addingTwoIdenticalGames
1. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест проходит
*Фактический результат:* Тест не проходит

# Скриншот
<img width="1189" alt="Снимок экрана 2023-01-30 в 12 59 01" src="https://user-images.githubusercontent.com/112762989/215446004-a4315d9a-50b7-45fe-b155-1415cd57929b.png">

#Окружение
* **Операционная система:** macOS Monterey 12.6
* **IDE:** intelliJ IDEA 2022.2.4 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by KhalilovaIrina** [comment]
![3](https://user-images.githubusercontent.com/117723193/215748141-46328a10-d861-46e1-8592-05f8c1b2e96b.png)
