### ISSUE TITLE
Метод getSumPlayedTime не реализован

### ISSUE THREAD

**Issue by Logerr23** [Logerr23/javaqa-team-diplom#6]
# Описание
Метод getSumPlayedTime не суммирует общее количество времени всех игроков, проведённого за играми каталога.

# Локация дефекта
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/GameStore.java#L75

# Шаги Воспроизведения

1. Открыть [код программы](https://github.com/Logerr23/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
1. Воспроизвести тест getSumPlayedTimeTest
1. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест проходит
*Фактический результат:* Тест не проходит

# Скриншот
<img width="1024" alt="Снимок экрана 2023-01-30 в 13 01 36" src="https://user-images.githubusercontent.com/112762989/215446512-d46f6118-e537-4c7a-8952-ee075ee51724.png">

#Окружение
* **Операционная система:** macOS Monterey 12.6
* **IDE:** intelliJ IDEA 2022.2.4 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by KhalilovaIrina** [comment]
![2](https://user-images.githubusercontent.com/117723193/215747856-7ea1c85d-15fe-4d56-8b67-179ccf42e0cd.png)
