### ISSUE TITLE
Метод getMostPlayer возвращает null, если в игры каталога играли не более часа

### ISSUE THREAD

**Issue by Logerr23** [Logerr23/javaqa-team-diplom#7]
# Описание
Метод getMostPlayer не возвращает имя игрока, который играл в игры этого каталога больше всего времени, если все игроки играли в игры этого каталога не более одного часа.

# Локация дефекта
https://github.com/Logerr23/javaqa-team-diplom/blob/37cbc8801c09fe3493d2676e14118a6dee07069a/src/main/java/ru/netology/GameStore.java#L59

# Шаги Воспроизведения

1. Открыть [код программы](https://github.com/Logerr23/javaqa-team-diplom/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA
1. Воспроизвести тест getMostPlayerTestAllplayedOneHour
1. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест проходит
*Фактический результат:* Тест не проходит

# Скриншот
<img width="1101" alt="Снимок экрана 2023-01-30 в 13 03 28" src="https://user-images.githubusercontent.com/112762989/215446935-1c1370a4-da0b-453d-8147-51a66363038e.png">

#Окружение
* **Операционная система:** macOS Monterey 12.6
* **IDE:** intelliJ IDEA 2022.2.4 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by KhalilovaIrina** [comment]
![image](https://user-images.githubusercontent.com/117723193/215747554-844eb7d2-7cc3-4124-b50a-cc3c9d682c84.png)
