### ISSUE TITLE
Игра устанавливается повторно, соответсвенно, время игры обнуляется.

### ISSUE THREAD

**Issue by KhalilovaIrina** [Logerr23/javaqa-team-diplom#8]
# Описание
При попытке повторно установить игру, которая уже есть в коллекции, с помощью метода *installGame*, игра успешно устанавливается и значение *playedTime* обнуляется.

# Локализация дефекта
https://github.com/Logerr23/javaqa-team-diplom/blob/14af7cc58b5e3054514bcf2af42c716bf1a2acda/src/main/java/ru/netology/Player.java#L24
https://github.com/Logerr23/javaqa-team-diplom/blob/14af7cc58b5e3054514bcf2af42c716bf1a2acda/src/main/java/ru/netology/Player.java#L26

# Шаги воспроизведения:
1. Открыть код программы https://github.com/Logerr23/javaqa-team-diplom.git в IDE.
2. Запустить тест *shouldNotInstallAlreadyExistGame()*.

*Ожидаемый результат* : Тест пройден
*Фактический результат* : Тест провален.

# Скриншот
![Баг 4](https://user-images.githubusercontent.com/117723193/215751743-25acc6f9-0294-40e8-b069-6848c9db0104.png)

# Окружение
* **Операционная система: Windows 10 Pro**
* **IDEA: IntelliJ IDEA 2022.3 (Community Edition**
* **Java: OpenJDK11**

**Comment by Logerr23** [comment]
<img width="950" alt="Снимок экрана 2023-02-02 в 13 17 51" src="https://user-images.githubusercontent.com/112762989/216298125-d8f80f7b-a47e-4087-bfdb-5f8d08a4887a.png">
